config/routes.rb
Factory::Application.routes.draw do
  resources :engines

  resources :fuels

  resources :vehicle_types

  devise_for :users
  resources :users, :controller => "users" do
    collection do
      get 'change_password'
      get 'admin_settings'
      get 'change_admin'
      post 'change_admin'
    end
  end  

  resources :user_details

  resources :constructions

  
  resources :vehicles do
    member do
      get 'info'
      get 'engine_data'
    end

    collection do
      get 'engine_data'
    end
  end

  match 'user_accesses/:id/allocate_users' => 'user_access#allocate_users', :as => :allocate_users

  match 'user_accesses/:id/add_more_vehicles' => 'user_access#add_more_vehicles', :as => :more_vehicles

  match 'user_accesses/:id/share_vehicles_with_users' => 'user_access#share_vehicles_with_users', :as => :share_vehicles_with_users
  
  match 'user_accesses/:id/unshare_vehicle' => 'user_access#unshare_vehicle', :as => :unshare_vehicle
  
  match 'user_accesses/:id/share_vehicle' => 'user_access#share_vehicle', :as => :share_vehicle

  root :to => 'site#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :admin, :user_detail_attributes
  attr_accessible :status
  has_one :user_detail, dependent: :destroy
  accepts_nested_attributes_for :user_detail
  has_many :user_accesses
  has_many :vehicles, through: :user_accesses 

  # The first registered user in the system should be admin.
  def self.one_admin
    first_user = User.all.first
    user =  User.all[1]

    if user.blank? && !first_user.blank? 
      user = User.first
      user.update_attributes(:admin => true)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	#before_filter :authenticate_user!
  
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new
    @user.build_user_detail

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'user was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'user was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
  
  # Admin settings
  def admin_settings
    @users = User.all
  end
  
  # Transfer admin privileges to another user
  def change_admin
    if params[:old_admin] && params[:user_id]
      #create new admin
      new_admin = User.find(params[:user_id])
      new_admin.update_attributes(:admin => true) 

      #delete old admin
      old_admin = User.find(params[:old_admin])
      old_admin.update_attributes(:admin => false)
    end
    flash[:notice] = "Your admin priviliges has been changed. You can access your account as a normal user"
    redirect_to root_path
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%# @user.build_user_detail %>
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, :autofocus => true %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  

  <%= f.fields_for :user_detail do |detail| %>
    <div class="field">
      <%= detail.label :first_name %><br />
      <%= detail.text_field :first_name %>
    </div>

    <div class="field">
      <%= detail.label :last_name %><br />
      <%= detail.text_field :last_name %>
    </div>

    <div>
      <%= detail.label :age %></br>
      <%= detail.text_field :age, :class => "left", :id => "field", :name => "field" %>
    </div>

    <div>
      <%= detail.label :sex %></br>
      <%= detail.select :sex, options_for_select([["Select One", ""],"Male", "Female"])%>
    </div></br>

    <div>
      <%= detail.label :phone %></br>
      <%= detail.text_field :phone %>
    </div></br>

    <div class="actions">
      <%= f.submit %>
    </div>
  <%end%>
  
<% end %>


<script>
// just for the demos, avoids form submit
jQuery.validator.setDefaults({
debug: true,
success: "valid"
});
$( "#new_user" ).validate({
rules: {
  field: {
    required: true,
    number: true
    }
  }
});
</script>

app/views/users/admin_settings.html.erb
<h2> Admin Settings </h2>
<span class="label label-success">Choose an user to transfer admin privileges.</span>
<%= link_to 'Back', root_path, :class => "pull-right" %><br/>
<%= form_tag change_admin_users_path(:old_admin => current_user.id) do %>

	<div class="well well-lg">
	  <!-- Table -->
	  <table class="table">
	    <tr>
	      <th>First Name</th>
	      <th>Last Name</th>
	      <th>Age</th>
	      <th>Sex</th>
	      <th>Phone</th>
	      <th>Email</th>
	      <th>Select</th>
	      <th></th>
	    </tr>
	    <% @users.each do |user| %>
	      <tr>
	          <td><%= user.user_detail.first_name %></td>
	          <td><%= user.user_detail.last_name %></td>
	          <td><%= user.user_detail.age %></td>
	          <td><%= user.user_detail.sex %></td>
	          <td><%= user.user_detail.phone %></td>
	          <td><%= user.email %></td>
	        <% if user.admin %>
	          <td><%=radio_button_tag 'user_id', user.id, true, 
          options = {}%></td>
	          <td><%= "Admin" %></td>
	        <% else %>
	          <td><%=radio_button_tag 'user_id', user.id, false, 
          options = {}%></td>
	          <td><%= "User" %></td>
	        <% end %>  
	      </tr>
	    <% end %>
	  </table>
	</div>
	<%= submit_tag 'Make Admin'%>
<% end %>	

app/views/users/index.html.erb
<h2>Listing users</h2>

<%= link_to 'New user', new_user_path %><%= link_to 'Back', root_path, :class => "pull-right" %><br/><br/>

<div class="well well-lg">
  <!-- Table -->
  <table class="table">

    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Age</th>
      <th>Sex</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Created by</th>
      <th>Actions</th>
    </tr>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.user_detail.first_name %></td>
        <td><%= user.user_detail.last_name %></td>
        <td><%= user.user_detail.age %></td>
        <td><%= user.user_detail.sex %></td>
        <td><%= user.user_detail.phone %></td>
        <td><%= user.email %></td>
    
        <% if user.admin %>
          <td><%= "Admin" %></td>
        <% else %>
          <td><%= "User" %></td>
        <% end %>

        <% if current_user.admin? %>  
          <td><%= link_to 'Show', user %></td>
          <td><%= link_to 'Edit', edit_user_path(user) %></td>
          <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        <% end %>
      </tr>    
    <% end %>
  </table>
</div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First Name:</b>
  <%= @user.user_detail.first_name %>
</p>

<p>
  <b>Last Name:</b>
  <%= @user.user_detail.last_name %>
</p>

<p>
  <b>Age:</b>
  <%= @user.user_detail.age %>
</p>

<p>
  <b>Sex:</b>
  <%= @user.user_detail.sex %>
</p>

<p>
  <b>Phone:</b>
  <%= @user.user_detail.phone %>
</p>

<p>
  <b>Phone:</b>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> | 
<% if user_signed_in?%>
  <% if current_user.admin? %>
    <%= link_to 'Back', users_path %>
  <% else %>  
    <%= link_to 'Back', root_path %>
  <% end %>
<% end %>