config/routes.rb
Factory::Application.routes.draw do
  resources :engines

  resources :fuels

  resources :vehicle_types

  devise_for :users
  resources :users, :controller => "users" do
    collection do
      get 'change_password'
      get 'admin_settings'
      get 'change_admin'
      post 'change_admin'
    end
  end  

  resources :user_details

  resources :constructions

  
  resources :vehicles do
    member do
      get 'info'
      get 'engine_data'
    end

    collection do
      get 'engine_data'
    end
  end

  match 'user_accesses/:id/allocate_users' => 'user_access#allocate_users', :as => :allocate_users

  match 'user_accesses/:id/add_more_vehicles' => 'user_access#add_more_vehicles', :as => :more_vehicles

  match 'user_accesses/:id/share_vehicles_with_users' => 'user_access#share_vehicles_with_users', :as => :share_vehicles_with_users
  
  match 'user_accesses/:id/unshare_vehicle' => 'user_access#unshare_vehicle', :as => :unshare_vehicle
  
  match 'user_accesses/:id/share_vehicle' => 'user_access#share_vehicle', :as => :share_vehicle

  root :to => 'site#index'

end

app/controllers/user_access_controller.rb
class UserAccessController < ApplicationController
  before_filter :authenticate_user!
  # Unshare shared vehicle.
	def unshare_vehicle
    if params[:vehicle_id] && params[:shared_by] && params[:id]
      @vehicle = UserAccess.where(:user_id => params[:id],:vehicle_id => params[:vehicle_id], :shared_by => params[:shared_by]).first
      @vehicle.destroy
      flash[:notice] = "Vehicle unshared"
    end

    respond_to do |format|
      format.js   { render :layout => false }
    end  
  end  

  # Share vehicles with other users.
  def share_vehicle
    if params[:vehicle_id] && params[:shared_by] && params[:id]
      @vehicle = UserAccess.create(:user_id => params[:id],:vehicle_id => params[:vehicle_id], :shared_by => params[:shared_by])
      flash[:notice] = "Vehicle shared"
    end

    respond_to do |format|
      format.js   { render :layout => false }
    end  
  end# End of method share_vehicle.

  # Admin can allocate vehicles to users.
	def allocate_users
    @vehicle = Vehicle.where("id = ?", params[:id])
    @users = User.all
    get_list

    if params[:vehicle_id]  #Allocating vehicles to users.
      users = Array.new
      params.each do |key,value|
        users << value if key.starts_with?'check'
      end

      users.each do |user|
       UserAccess.create(:user_id => user,:vehicle_id => params[:vehicle_id], :shared_by => params[:shared_by], :appointment_date => Time.now)
       flash[:notice] = "Vehicles alotted to users successfully"
      end
    end
 	end# End of method allocate_users.
  
  # User can add more vehicles to work on.
	def add_more_vehicles
    @vehicles = Vehicle.order(:vehicle_type)

    if params[:user_id] 
      vehicles = Array.new
      params.each do |key,value|
        vehicles << value if key.starts_with?'check'
      end

      vehicles.each do |vehicle|
        UserAccess.create(:user_id => params[:id],:vehicle_id => vehicle, :shared_by => params[:id], :appointment_date => Time.now)
        flash[:notice] = "Vehicles added successfully"
      end
      redirect_to :vehicles
    end
  end# End of method add_more_vehicles.
  
  # User can share vehicle with other users.
  def share_vehicles_with_users
    @vehicle = Vehicle.where("id = ?", params[:id])
    @users = User.all
    get_list
    
    if params[:vehicle_id]
      @vehicle = Vehicle.where("id = ?", params[:id])
      @users = User.all
      get_list

      #Allocating vehicles to users
      users = Array.new
      params.each do |key,value|
        users << value if key.starts_with?'check'
      end

      users.each do |user|
        UserAccess.create(:user_id => user,:vehicle_id => params[:vehicle_id], :shared_by => params[:shared_by], :appointment_date => Time.now)
        flash[:notice] = "Vehicles alotted to users successfully"
      end
    end # End of IF BLOCK.
  end # End of method share_vehicles_with_users.
end # End od Class.   

app/helpers/user_access_helper.rb
module UserAccessHelper
end

app/views/user_access/add_more_vehicles.html.erb
<h2>Add more vehicles</h2>
<div class="pull-right">
  <%= link_to "Back", vehicles_path%>
</div><br/>

<%= form_tag more_vehicles_path do %>
  <div class="well well-sm">
    <!-- Table -->
    <table class="table">
      <tr>
        <th>Type</th>
        <th>Occupants</th>
        <th>Payload weight</th>
        <th>Vehicle identifier</th>
        <th>Details</th>
        <th>Select</th>
        <th></th>
      </tr>

      <% @vehicles.each do |vehicle| %>  
        <tr>
          <% unless current_user.admin?%>
            <td><%= vehicle.vehicle_type %></td>
            <% if vehicle.vehicle_type == "Shuttle"%>
              <td><%= vehicle.occupants %></td>
            <% else%>
              <td>NA</td>
            <% end %>
            <% if vehicle.vehicle_type == "Satellite"%>
              <td><%= vehicle.payload_weight %></td>
            <% else%>
              <td>NA</td>
            <% end %> 
            <td><%= vehicle.v_identifier %></td>  
            <td><%= link_to 'Show', vehicle %></td>
            <td><%= check_box_tag("check#{vehicle.id}", value = "#{vehicle.id}", checked = false )%>
            </td>
            <td><%= hidden_field_tag 'user_id', current_user.id %></td><br/> 
          <% end %>
        </tr>
      <% end %>
    </table><br/>
  </div>
  <div class="pull-right">
    <%= submit_tag "Add"%>
  </div><br/><br/>
<% end %>

app/views/user_access/allocate_users.html.erb
<h2>Allocate <%= @vehicle.first.vehicle_type %>-<%=  @vehicle.first.v_identifier %> to users</h2>

<%= form_tag allocate_users_path do %>
  <%=hidden_field_tag 'vehicle_id', @vehicle.first.id %>
  <%=hidden_field_tag 'shared_by', current_user.id%>
  <table>
    <tr>
      <th>Type</th>
      <th>Occupants</th>
      <th>Payload weight</th>
      <th>Vehicle identifier</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>

    <% @users.each do |user| %>  
      <tr>
        <% unless user.admin?%>
          <td><%= user.user_detail.first_name %></td>
          <td><%= user.user_detail.last_name %></td>
          <td><%= user.user_detail.age %></td>
          <td><%= user.user_detail.sex %></td>
          <td><%= link_to 'Show', user %></td>
          <td><%=check_box_tag("check#{user.id}", value = "#{user.id}", checked = false, 
          options = {})%>
          </td><br/> 
        <% end %>
      </tr>
    <% end %>
  </table><br/>
  <%= submit_tag "Allocate"%><br />  
<% end %>

app/views/user_access/share_vehicle.js.erb
//code for changing unshared to shared
alert("Vehicle Shared")

app/views/user_access/share_vehicles_with_users.html.erb
<h2>Allocate vehicle to users</h2>

<%#= form_tag share_vehicles_path do %>
  <%#=select_tag "vehicle", @vehicles %>
  <%#=hidden_field_tag 'vehicle_id', @vehicle.first.id %>
  <%#=hidden_field_tag 'shared_by', current_user.id%>
  <table>
    <tr>
      <th>Type</th>
      <th>Occupants</th>
      <th>Payload weight</th>
      <th>Vehicle identifier</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>

    <% @users.each do |user| %>  
      <tr>
        <% if !user.admin? && user.id != current_user.id%>
          <td><%= user.user_detail.first_name %></td>
          <td><%= user.user_detail.last_name %></td>
          <td><%= user.user_detail.age %></td>
          <td><%= user.user_detail.sex %></td>
          <td><%= link_to 'show', user %></td>
            <% shared = UserAccess.where(:shared_by => current_user.id, :user_id => user.id, :vehicle_id => @vehicle.first.id, ) %>
            <% if shared.blank? %>
              <td id="share"><%= link_to 'share', share_vehicle_path(user, :vehicle_id => @vehicle.first.id, :shared_by => current_user.id ), :remote => true %>
              </td><br/>
            <% else %>
              <td id="unshare"><%= link_to 'unshare', unshare_vehicle_path(user, :vehicle_id => @vehicle.first.id, :shared_by => current_user.id ), :remote => true %>
              </td>
            <% end %>   
        <% end %>
      </tr>
    <% end %>
  </table>

<%#= submit_tag "Share"%><br />  
  
<%# end %>

app/views/user_access/unshare_vehicle.js.erb
alert("Vehicle Unshared...")