config/routes.rb
Factory::Application.routes.draw do
  resources :engines

  resources :fuels

  resources :vehicle_types

  devise_for :users
  resources :users, :controller => "users" do
    collection do
      get 'change_password'
      get 'admin_settings'
      get 'change_admin'
      post 'change_admin'
    end
  end  

  resources :user_details

  resources :constructions

  
  resources :vehicles do
    member do
      get 'info'
      get 'engine_data'
    end

    collection do
      get 'engine_data'
    end
  end

  match 'user_accesses/:id/allocate_users' => 'user_access#allocate_users', :as => :allocate_users

  match 'user_accesses/:id/add_more_vehicles' => 'user_access#add_more_vehicles', :as => :more_vehicles

  match 'user_accesses/:id/share_vehicles_with_users' => 'user_access#share_vehicles_with_users', :as => :share_vehicles_with_users
  
  match 'user_accesses/:id/unshare_vehicle' => 'user_access#unshare_vehicle', :as => :unshare_vehicle
  
  match 'user_accesses/:id/share_vehicle' => 'user_access#share_vehicle', :as => :share_vehicle

  root :to => 'site#index'

end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  	User.one_admin # First registered user should be admin

  	# Check if user has logged in.
  	redirect_to new_user_session_path unless user_signed_in?
  end
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/site/index.html.erb
<div class="container">	
	<% if user_signed_in? %>
		<div>
	   	<% if !flash[:notice].blank? %>
	    	<div class="alert alert-success" id="test">
	      	Signed In Successfully
	    	</div>
    	<%end%>
  	</div>
	  <% unless current_user.admin? %>
	    <h2>Welcome <%=current_user.user_detail.first_name.capitalize%></h2>
	  <% else %>	
	    <h2>Welcome Admin</h2>
	  <% end%>
    <div class="well well-lg">
      <ul class="nav nav-pills nav-stacked">
  			<li class="active">
    			<%= link_to 'Admin Options', root_path if current_user.admin? %>
    			<%= link_to 'User Options', root_path unless current_user.admin? %>
  			</li>
			</ul>

    	<div class="panel-body"> 
				<% if current_user.try(:admin?) %>
					<ul class="nav nav-pills nav-stacked ">
				  	<li> <%= link_to 'Users', users_path %> </li>
				  	<li> <%= link_to 'Vehicles', vehicles_path %> </li>
				  	<li> <%= link_to 'Vechicle types', vehicle_types_path %> </li>
				  	<li> <%= link_to 'Engines', engines_path %> </li>
				  	<li> <%= link_to 'Fuels', fuels_path %> </li>
				  	<li> <%= link_to 'Vehicle Constructions', constructions_path %> </li>
				  	<li> <%= link_to 'Admin Settings', admin_settings_users_path %> </li>
				  </ul>	
				<% elsif current_user %>
				  <ul class="nav nav-pills nav-stacked ">  	
				  	<li> <%= link_to 'Vehicles', vehicles_path %> </li>
				  	<li> <%= link_to 'Profile', current_user%> </li>
				  </ul>	
				<% end %>
			</div>	
		</div>
	<% end %>
</div>	