config/routes.rb
Factory::Application.routes.draw do
  resources :engines

  resources :fuels

  resources :vehicle_types

  devise_for :users
  resources :users, :controller => "users" do
    collection do
      get 'change_password'
      get 'admin_settings'
      get 'change_admin'
      post 'change_admin'
    end
  end  

  resources :user_details

  resources :constructions

  
  resources :vehicles do
    member do
      get 'info'
      get 'engine_data'
    end

    collection do
      get 'engine_data'
    end
  end

  match 'user_accesses/:id/allocate_users' => 'user_access#allocate_users', :as => :allocate_users

  match 'user_accesses/:id/add_more_vehicles' => 'user_access#add_more_vehicles', :as => :more_vehicles

  match 'user_accesses/:id/share_vehicles_with_users' => 'user_access#share_vehicles_with_users', :as => :share_vehicles_with_users
  
  match 'user_accesses/:id/unshare_vehicle' => 'user_access#unshare_vehicle', :as => :unshare_vehicle
  
  match 'user_accesses/:id/share_vehicle' => 'user_access#share_vehicle', :as => :share_vehicle

  root :to => 'site#index'

end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  attr_accessible :occupants, :payload_weight, :vehicle_type, :v_identifier, :engine_id, :construction_attributes
  validates :occupants, :numericality => {:only_integer => true}
  validates :v_identifier, :numericality => {:only_integer => true}  
  has_many :user_accesses
  has_many :users, through: :user_accesses
  has_one :construction, dependent: :destroy
  belongs_to :engine
  accepts_nested_attributes_for :construction
end

app/models/vehicle_type.rb
class VehicleType < ActiveRecord::Base
  attr_accessible :kind
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_filter :authenticate_user!
  # GET /vehicles
  # GET /vehicles.json
  def index
    if current_user.admin?
      @vehicles = Vehicle.order(:vehicle_type)
    else
      @vehicles = current_user.vehicles
    end   
       
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @vehicles }
    end
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
    @vehicle = Vehicle.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @vehicle }
    end
  end

  # GET /vehicles/new
  # GET /vehicles/new.json
  def new
    @vehicle = Vehicle.new
    @vehicle.build_construction
    get_list

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @vehicle }
    end
  end

  # GET /vehicles/1/edit
  def edit
    @vehicle = Vehicle.find(params[:id])
    get_list
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    engine = Engine.where(:model => params[:vehicle][:engine_id] )
    params[:vehicle][:engine_id] = engine.first.id
    @vehicle = Vehicle.new(params[:vehicle])

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to action: "index", notice: 'Vehicle was successfully created.' }
        format.json { render json: @vehicle, status: :created, location: @vehicle }
      else
        format.html { render action: "new" }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /vehicles/1
  # PUT /vehicles/1.json
  def update
    @vehicle = Vehicle.find(params[:id])

    respond_to do |format|
      if @vehicle.update_attributes(params[:vehicle])
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle = Vehicle.find(params[:id])
    if @vehicle.construction.delivery_date < Time.now
      respond_to do |format|
        if @vehicle.destroy
          flash[:notice] = " Vehicle deleted successfully."
          format.html { redirect_to vehicles_url }
          #format.json { head :no_content }
          format.js   { render :layout => false }
        else
          flash[:error] = "Sorry! Vehicle delivery date has not passed yet."
          format.html { render action: "index" }
          #format.js   { render :layout => false }
        end
      end 
    end
  end
  
  # Vehicle information JSON response 
  def info
    puts "In info"
    # First information url shows identifier,engine information and list of users
    if params[:info] == "first_url"
      @vehicle = Vehicle.find(params[:id])
      @identifier = @vehicle.v_identifier
      @engine = @vehicle.engine
      @users = @vehicle.users
        render :json => {
          :identifier => @identifier,
          :engine => @engine,
          :users => @users
        }
    # Second information url shows identifier,engine information and vehicle delivery date
    elsif params[:info] == "second_url"
      @vehicle = Vehicle.find(params[:id])
      @identifier = @vehicle.v_identifier
      @engine = @vehicle.engine
      @delivery_date = @vehicle.construction.delivery_date.to_date
        render :json => {
          :identifier => @identifier,
          :engine => @engine,
          :delivery_date => @delivery_date
        }
    end
  end

  def engine_data 
    if params[:engine_model]
      @power = Engine.where(:model => params[:engine_model]).first.power_rating
      respond_to do |format|
        #format.json { render :json => @power.to_json}
        format.js { render :layout => false, :locals => {:power => @power} } 
      end
    end
  end  
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/vehicles/_form.html.erb
<div class="well well-sm">
  <%= form_for(@vehicle, :html => {:class => "container"}) do |f| %>
    <% if @vehicle.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

        <ul>
          <% @vehicle.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :vehicle_type %><br />
      <%= f.select :vehicle_type, @vehicle_types %>
    </div>
    <div>
      <%= f.label :vehicle_engine %><br />
      <%= f.select :engine_id, @engines%>
      <%= label_tag 'name', 'Power'%>
      <%= text_field_tag :power, nil, :disabled => true %>
    </div><br/>
    <div class="field" id="occupants">
      <%= f.label :occupants %><br />
      <%= f.number_field :occupants %>
    </div>
    <div class="field" id="payload_weight(Kgs)">
      <%= f.label :payload_weight_in_kgs %><br />
      <%= f.text_field :payload_weight, :disabled => true %>
    </div>
    <div class="field">
      <%= f.label :vehicle_identifier %><br />
      <%= f.number_field :v_identifier, :maxlength => 4, :placeholder => "(Four digit number only)" %>
    </div>
    <%= f.fields_for :construction do |ff| %>
      <div>
        <%= ff.label :start_date %><br/>
        <%= ff.date_select :start_date %>
      </div><br/>
      <div>
        <%= ff.label :delivery_date %><br/>
        <%= ff.date_select :delivery_date %>
      </div><br/>
    <% end %>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

 

app/views/vehicles/_message.html.erb
<div class="alert alert-success" id="test">
  <%=flash[:error]%>
</div>  

app/views/vehicles/_vehicles_list.html.erb
<!-- Vehicles Listing -->
<% unless @vehicles.blank?%>
  <table class="table">
    <tr>
      <th>Type</th>
      <th>Occupants</th>
      <th>Payload weight</th>
      <th>Vehicle identifier</th>
      <th>Construction Start date</th>
      <th>Construction Delivery date</th>
      <th></th>
      <th></th>
      <th></th>
      <th>Share</th>
    </tr>

    <% @vehicles.each do |vehicle| %>
      <tr>
        <td><%= vehicle.vehicle_type %></td>
        <% if vehicle.vehicle_type == "Shuttle"%>
          <td><%= vehicle.occupants %></td>
        <% else%>
          <td>NA</td>
        <% end %>
        <% if vehicle.vehicle_type == "Satellite"%>
          <td><%= vehicle.payload_weight %></td>
        <% else%>
          <td>NA</td>
        <% end %>  
        <td><%= vehicle.v_identifier %></td>
        <td><%= vehicle.construction.start_date.to_date %></td>
        <td><%= vehicle.construction.delivery_date.to_date %></td>
        <td><%= link_to 'Show', vehicle %></td>
        <td><%= link_to 'Edit', edit_vehicle_path(vehicle) %></td>
        <td><%= link_to 'Destroy', vehicle, method: :delete, data: { confirm: 'Are you sure?' }, :remote => true, :class => 'delete_vehicle' %>
        </td>
        <% if current_user.admin? %>
          <td><%= link_to 'Allocate users', allocate_users_path(vehicle) %></td>
        <% else %>      
          <td><%= link_to 'Share to users', share_vehicles_with_users_path(vehicle) %></td>
        <%end%>      
      </tr>
    <% end %>
  </table>
<% else %>
  <div class="panel-body panel-warning">
    <center>
      <strong> No vehicles assigned yet, please add vehicle. </strong>
    </center>
  </div>
<% end %>
<!-- Vehicles List

app/views/vehicles/destroy.js.erb
$('.delete_vehicle').bind('ajax:success', function() {  
        $(this).closest('tr').fadeOut();
});

$('#notification').html('<div class="alert alert-success" id="test">Vehicle Deleted</div> ');

$(document).ready(function() {
	setTimeout(function() {
	    $('#notification').fadeOut('slow');
	}, 3000);
});	

app/views/vehicles/engine_data.js.erb
$("#power").val("<%= power %>")
$("#vehicle_payload_weight").val("<%= power %>"/2)

app/views/vehicles/index.html.erb
<div class="container">
  <% if user_signed_in? %>
    <!-- Notifications  -->
    <% if flash[:error] %>
      <div class="alert alert-success" id="test">
        <%=flash[:notice]%>
      </div>
    <% elsif notice %> 
       <div class="alert alert-success" id="test">
        <%= notice%>
      </div>
    <% end %>
    <!-- Notifications  -->
    <div id="notification"></div>
    <h2>Listing vehicles</h2>
    <% if current_user.admin? %>
      <%= link_to 'New Vehicle', new_vehicle_path %> 
    <% else %>    
      <%= link_to 'Add Vehicles', more_vehicles_path(current_user)%>
    <% end %>
    <%= link_to 'Back', root_path, :class => "pull-right" %><br/><br/>
      
      <!-- Table -->
    <div class="panel panel-default well well-lg">
      <%= render 'vehicles_list' %>
    </div>
  <%end%>
</div>

app/views/vehicles/share_vehicles_with_users.html.erb
<h2>Allocate vehicle to users</h2>

<div class="well well-lg">
  <table class="table">
    <tr>
      <th>Type</th>
      <th>Occupants</th>
      <th>Payload weight</th>
      <th>Vehicle identifier</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>

    <% @users.each do |user| %>  
      <tr>
        <% if !user.admin? && user.id != current_user.id%>
          <td><%= user.user_detail.first_name %></td>
          <td><%= user.user_detail.last_name %></td>
          <td><%= user.user_detail.age %></td>
          <td><%= user.user_detail.sex %></td>
          <td><%= link_to 'Show', user %></td>
          <% shared = UserAccess.where(:user_id => user.id, :vehicle_id => @vehicle.first.id ) %>
          <% if shared.blank? %>
            <td><%= link_to 'share', share_vehicle_path(user, :vehicle_id => @vehicle.first.id, :shared_by => current_user.id ), :remote => true, :class => 'share' %>
            </td>
          <% else %>
            <td><%= link_to 'unshare', unshare_vehicle_path(user, :vehicle_id => @vehicle.first.id, :shared_by => current_user.id ), :remote => true, :class => 'unshare' %>
            </td>
          <% end %>   
        <% end %>
      </tr>
    <% end %>
  </table>
</div><br/>

app/views/vehicles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Type:</b>
  <%= @vehicle.vehicle_type %>
</p>

<% if @vehicle.vehicle_type == "Shuttle" %>
	<p>
	  <b>Occupants:</b>
	  <%= @vehicle.occupants %>
	</p>
<% else %>
	<p>
	  <b>Payload weight:</b>
	  <%= @vehicle.payload_weight %>
	</p>
<% end %>

<p>
  <b>V identifier:</b>
  <%= @vehicle.v_identifier %>
</p>

<span class="label label-warning">
	<%= link_to 'Vehicle Info 1', info_vehicle_path(@vehicle,:info => "first_url") %>
</span>
<span class="label label-warning">
	<%= link_to 'Vehicle Info 2', info_vehicle_path(@vehicle,:info => "second_url") %>
</span>

<%= link_to 'Edit', edit_vehicle_path(@vehicle) %> |
<%= link_to 'Back', vehicles_path %>